
CREATE USER 'miagenda'@'localhost' IDENTIFIED BY 'miagenda123$';

GRANT USAGE ON *.* TO 'miagenda'@'localhost';

ALTER USER 'miagenda'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON miagenda.* TO 'miagenda'@'localhost';

FLUSH PRIVILEGES;